### ISSUE TITLE
[Feature] Multisite Caching

### ISSUE THREAD

**Issue by lige-development** [luklewluk/SupercachePlugin#13]
As we do even large implementations with multisite environment and there is not any accessible setting for this matter, I found following bug:

- create multiple sites in pimcore backend
- set on caching including supercache

All incomming connections are now cached as index.html without any distinction, which site you're attempting to visit (always the very first request is being cached). Therefore it's necessary to create even the cached structure accordingly. I also did a patch to cover this bug (enclosed)

[ABA_127_Supercache_multisite_patch.zip](https://github.com/luklewluk/SupercachePlugin/files/561711/ABA_127_Supercache_multisite_patch.zip)

**Comment by lige-development** [comment]
I almost forgot - you also have to change the .htaccess settings accordingly:

`RewriteCond %{DOCUMENT_ROOT}/plugins/Supercache/webcache/%{HTTP_HOST}/$1/index.html -f
RewriteRule ^(.*) %{DOCUMENT_ROOT}/plugins/Supercache/webcache/%{HTTP_HOST}/$1/index.html [L]

RewriteCond %{DOCUMENT_ROOT}/plugins/Supercache/webcache/%{HTTP_HOST}/$1/index.js -f
RewriteRule ^(.*) %{DOCUMENT_ROOT}/plugins/Supercache/webcache/%{HTTP_HOST}/$1/index.js [L]

RewriteCond %{DOCUMENT_ROOT}/plugins/Supercache/webcache/%{HTTP_HOST}/$1/index.bin -f
RewriteRule ^(.*) %{DOCUMENT_ROOT}/plugins/Supercache/webcache/%{HTTP_HOST}/$1/index.bin [L]`

**Comment by luklewluk** [comment]
Thank you very much for the input @lige-development !
Could you create Pull Request with your patch?

**Comment by lige-development** [comment]
@luklewluk pull request created https://github.com/luklewluk/SupercachePlugin/pull/14

**Comment by luklewluk** [comment]
@lige-development thanks a lot!
